### PR TITLE
build number 4

### PR DESCRIPTION
**Pull request by dnadeau4**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by dnadeau4** [comment]
@conda-forge-admin, please rerender

**Comment by dnadeau4** [comment]
@ocefpaf @isuruf 
I think I broke my BINSTAR_TOKEN during the update.  I cannot get OSX.

Here is the message from Travis log....
```
Distribution /Users/travis/miniconda3/conda-bld/osx-64/cdms2-3.1.2-py27h3edfc39_4.tar.bz2 is new for conda-forge, but no upload is taking place because the BINSTAR_TOKEN is missing.
```

**Comment by dnadeau4** [comment]
@ocefpaf @isuruf I found which commit and was able to fix the BINSTAR_TOKEN. 😄

**Comment by ocefpaf** [comment]
> @ocefpaf @isuruf I found which commit and was able to fix the BINSTAR_TOKEN.

That was quick :smile: 

Thanks for fixing it!

**Pull request merged**
