### PR TITLE
Rebuild for `libnetcdf` 4.8.0

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
The conda-forge bot is failing to solve this on its own: 
https://conda-forge.org/status/
```
cdms2 (0) Error: not solvable (bot CI job): master: ['linux_64_numpy1.17python3.6.____cpython: Encountered problems while solving:\n - package libcf-1.0.1-py27_2 requires python 2.7*, but none of the providers can be installed\n', 'linux_64_numpy1.17python3.7.____cpython: Encountered problems while solving:\n - nothing provides openblas 0.3.5.* needed by libblas-3.8.0-4_openblas\n', 'linux_64_numpy1.17python3.8.____cpython: Encountered problems while solving:\n - package libcf-1.0.1-py27_2 requires python 2.7*, but none of the providers can be installed\n', 'linux_64_numpy1.19python3.9.____cpython: Encountered problems while solving:\n - package libcf-1.0.3-py39h9a4f717_109 requires libnetcdf >=4.7.4,<4.7.5.0a0, but none of the providers can be installed\n', 'osx_64_numpy1.17python3.6.____cpython: Encountered problems while solving:\n - nothing provides openblas 0.3.5.* needed by libblas-3.8.0-4_openblas\n', 'osx_64_numpy1.17python3.7.____cpython: Encountered problems while solving:\n - nothing provides openblas 0.3.5.* needed by libblas-3.8.0-4_openblas\n', 'osx_64_numpy1.17python3.8.____cpython: Encountered problems while solving:\n - nothing provides openblas 0.3.5.* needed by libblas-3.8.0-4_openblas\n', 'osx_64_numpy1.19python3.9.____cpython: Encountered problems while solving:\n - nothing provides openblas 0.3.5.* needed by libblas-3.8.0-4_openblas\n']
```
I'm going to see what I can do.

**Comment by xylar** [comment]
@jasonb5, the error here (`undefined symbol: _gfortran_malloc`) seems to be the same as we saw in https://github.com/conda-forge/cdtime-feedstock/pull/43.  Would the fix be an equivalent patch to https://github.com/conda-forge/cdtime-feedstock/pull/43/commits/ba2f4db2339e77e864d7a0adbbc98b68c52d4ef7?  If so, would you be willing to make one?  We need `cdms2` with `libnetcdf` 4.8.0 by June 1st (but sooner would be nice).  

If you're able to push a fix directly to this branch, please do so.  If not, maybe make a  commit on your own branch that I can cherry-pick, and point me to it.

Thanks a bunch!

**Comment by xylar** [comment]
I made my best go at it in a local build and it works but I'd rather have an expert do the patch.

**Comment by jasonb5** [comment]
@xylar I'll take a look first thing tomorrow.

**Comment by xylar** [comment]
@jasonb5, thanks so much!  The tests all pass.  Let me know if this is ready to merge.

**Comment by jasonb5** [comment]
@xylar It's ready to merge, forgot to check back on it last night. Thanks.

**Comment by xylar** [comment]
Great, thanks a bunch!

**Comment by chengzhuzhang** [comment]
Thank you @xylar  and @jasonb5 !

**Pull request merged**
