### PR TITLE
Add a patch to disable mpi4py with an env. var.

### PR DESCRIPTION
**Pull request by xylar**
This is similar to what was done in #68 for the `cdms2` package, but this time for the `regrid2` package and the `cdscan.py` script.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@jasonb5, I did some testing on Cori with the last build (6) and it works well for the code it covers!  We can use `e3sm_diags` on compute nodes with `mpi4py` but we still can't use it on login nodes by disabling MPI. The reason is that `regrid2` and `distarray` still import `mpi4py`, which causes a crash.  Here, I'm patching `regrid2` and in another commit, I'll patch `distarray` (and add us as maintainers of that feedstock).

**Comment by xylar** [comment]
Still running into trouble with `e3sm_diags` even with this patch.  Switching to draft until I figure more out.

**Comment by xylar** [comment]
@jasonb5, Okay, I tested this with `e3sm_diags` on a login node on Cori and everything I've tried now work as long as we set `CDMS_NO_MPI=True`.  (We don't need that on a compute node, where `mpi4py` works properly.)

Please let me know:
1. if you're okay with this patch and
2. if you would like me to make the equivalent PR to the main repo.

**Comment by jasonb5** [comment]
@xylar Weird didn't get any notifications for this. 

LGTM though, go ahead and make a PR in the main repo as well.

**Review by jasonb5 — APPROVED** [review]

**Comment by xylar** [comment]
@jasonb5, Oh, great! I didn't want to bug you about this because I know you have a lot else on your plate.  But I'll take care of this and also https://github.com/conda-forge/distarray-feedstock/pull/4, and I'll make the corresponding PRs to the upstream repos.

**Comment by jasonb5** [comment]
> @jasonb5, Oh, great! I didn't want to bug you about this because I know you have a lot else on your plate. But I'll take care of this and also [conda-forge/distarray-feedstock#4](https://github.com/conda-forge/distarray-feedstock/pull/4), and I'll make the corresponding PRs to the upstream repos.

@xylar Sounds good! Feel free next time to ping me on slack, it's not a bother, plus it gets it on my radar.

**Pull request merged**
