### PR TITLE
Rebuild v3.0.1 with new recipe

### PR DESCRIPTION
**Pull request by xylar**
This is needed because the existing recipe doesn't work with conda-build 3.16.3.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@dnadeau4 and @doutriaux1, I have this set to merge to master right now.  However, a better solution would be to merge to a temporary branch on the main `conda-forge/cdms2-feedstock` fork that we then discard.  This prevents us from having to revert the changes after the merge.

If one of you would just push the current `master` to a branch called something like `rebuild_v3.0.1`, that would be great!  Then, I can edit the PR to merge to that branch.

**Comment by dnadeau4** [comment]
We are now at version 3.1.2 which uses shared libraries for Mac OS X and Linux.  Do we need to do this?  @doutriaux1 told me that the latest CDMS works with CDAT.  I’ll look at it tomorrow on my machines first just to make sure it works with libcdms and libdrs 3.1.2 shared libraries

**Comment by xylar** [comment]
@dnadeau4, If we can get a set of conda packages that work with `cdms2=3.1.2`, that would be great!  `e3sm_diags` currently pins a set of packages that doesn't work with the latest `cdms2`:
https://github.com/E3SM-Project/e3sm_diags/blob/master/conda/meta.yaml#L19-L27
At least that's the way it seemed to me.

**Comment by dnadeau4** [comment]
```conda install -c conda-forge cdms2 libcdms ```

This should install everything 3.1.2

In your recipe, you have python {{python}} which downgrade OpenSSL.  That caused me a lot of issue since  the latest libcurl uses 1.1 OpenSSL.  I am still trying to find a solution.  Condaforge would need to recompile python

**Comment by xylar** [comment]
I think the issue with `esmf` version number is an issue with the latest `conda` (and `conda-build`), see https://github.com/conda/conda/issues/8309

I'm going to close this PR.

Thanks for the advice regarding the recipe, @dnadeau4

**Comment by dnadeau4** [comment]
@xylar this is true for cdms 3.0  I unpinned ESMF for cdms 3.1.2, so this problem is not encountered.

**Comment by xylar** [comment]
Yes, will work with @zshaheen to see if we can build a version of `e3sm_diags` with a newer version of `cdms2`.  I do think that's a good solution and I have now (thanks to your suggestion) found a group of `cdat` packages that are compatible with one another.

**Pull request closed without merging**
