### PR TITLE
Rebuild for gfortran 7 for OSX (fixed)

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #34

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge/cdms2 Somewhere there is a linking problem with the library version of libnetcdf. It seems to build against 13 but then try and load 11 at run time. I think this means that some dep was built against a version that is too old. It looks like cdtime maybe, but cdtime has no direct dependence.

**Comment by beckermr** [comment]
I have attempted to rebuild cdtime here to see what happens. 

https://github.com/conda-forge/cdtime-feedstock/pull/22

However, if libnetcdf is shipping different library versions without a corresponding version bump in the metadata accessible to conda, then we need to fix how that is packaged.

@conda-forge/libnetcdf for viz

**Comment by beckermr** [comment]
OK. The build appears to work now. Note that I have added libnetcdf to the host/run section because the resulting libraries are linked to it, but the package is not specified explicitly. This should help prevent weird errors in future migrations.

**Comment by doutriaux1** [comment]
@muryanto1 @downiec make sure to propagate the recipe changes to our repo

**Pull request merged**
