### PR TITLE
try to rebuild with  >=4.6.2,<4.6.3.0a0 -- just for testing

### PR DESCRIPTION
**Pull request by muryanto1**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by muryanto1** [comment]
@conda-forge-admin, please rerender

**Comment by muryanto1** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@muryanto1, the error under python 3.7, OSX seems to be for the same test that we had problems with in #43 with python 3.8.  The build is too old and the log no longer exists, so we'd have to rebuild to be sure.

**Comment by muryanto1** [comment]
This PR was just for testing with an older version of libnetcdf. Closing it.

**Pull request closed without merging**
